force-app/main/default/objects/Account_Territory__c/Account_Territory__c.object-meta.xml
<CustomObject>
    <label>Account Territory</label>
    <nameField>
        <label>Account Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Territory__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Territories</relationshipLabel>
    <relationshipName>Account_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Territory__c/fields/Territory_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Territory_Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Coverage</label>
    <referenceTo>Territory_Coverage__c</referenceTo>
    <relationshipLabel>Account Territories</relationshipLabel>
    <relationshipName>Account_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Coverage__c/Territory_Coverage__c.object-meta.xml
<CustomObject>
    <label>Territory Coverage</label>
    <nameField>
        <label>Territory Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Coverage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Field_Crew_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Field_Crew_End_Time__c</fullName>
    <inlineHelpText>Auto populated field that captures the time field crew worker clocked out at job</inlineHelpText>
    <label>Field Crew End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Invoice_Notes_Options__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Notes_Options__c</fullName>
    <label>Invoice Notes Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Carpet Roll</fullName>
            </value>
            <value>
                <fullName>Wear That Looks Like Soil</fullName>
            </value>
            <value>
                <fullName>Banding</fullName>
            </value>
            <value>
                <fullName>Bleaching</fullName>
            </value>
            <value>
                <fullName>Pivot Wear</fullName>
            </value>
            <value>
                <fullName>Residual Urine Smell</fullName>
            </value>
            <value>
                <fullName>Stain Magic</fullName>
            </value>
            <value>
                <fullName>High Levels Of Pet Hair</fullName>
            </value>
            <value>
                <fullName>Carpet Illusions After Cleaning</fullName>
            </value>
            <value>
                <fullName>Furniture Divots</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Property_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Property_Zip_Code__c</fullName>
    <label>Property Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending IC</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending ICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Van_assignment__c.field-meta.xml
<CustomField>
    <fullName>Van_assignment__c</fullName>
    <label>Van assignment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Van 1</fullName>
                <color>#FFFF66</color>
                <label>Van 1</label>
            </value>
            <value>
                <fullName>Van 2</fullName>
                <color>#CC33CC</color>
                <label>Van 2</label>
            </value>
            <value>
                <fullName>Van 3</fullName>
                <color>#3333FF</color>
                <label>Van 3</label>
            </value>
            <value>
                <fullName>Van 4</fullName>
                <color>#33CC00</color>
                <label>Van 4</label>
            </value>
            <value>
                <fullName>Van 5</fullName>
                <color>#66FF99</color>
                <default>true</default>
                <label>Van 5</label>
            </value>
            <value>
                <fullName>Team Van</fullName>
                <color>#FF9900</color>
                <label>Team Van</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <label>Commercial</label>
</RecordType>

force-app/main/default/classes/superCloneController_Test.cls
@isTest
private class superCloneController_Test {

	private static testMethod void test() {
	    Work_Order__c workOrdr = new Work_Order__c();
	    workOrdr.recordTypeId = Schema.SObjectType.Work_Order__c.getRecordTypeInfosByName().get('Commercial').getRecordTypeId() ;
	    workOrdr.Van_assignment__c = 'van 5';
	    workOrdr.Status__c ='Invoiced';
	    workOrdr.Field_Crew_End_Time__c = system.now();
	    insert workOrdr;
	    
        PageReference pageRef = Page.superClonePage;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('id', workOrdr.id);
        
        //superCloneController controller = new superCloneController(); 
        
        ApexPages.StandardController stdcontroller = new ApexPages.StandardController(workOrdr);
    
        superCloneController controller = new superCloneController(stdcontroller);    
        
        
        controller.cloneRecord();
	}
    
    private static testMethod void ShareWorkOrder(){
        //User u = [SELECT id from User where Profile.Name = 'Customer Community User - Custom'];
        Profile p =[select id from Profile where Name = 'Franchise Partner Community'];        
            
        account acc = new account();
        acc.name = 'Damco test account';
        insert acc;
        
        contact con = new contact();
        con.LastName = 'Damco invoice';
        con.Email = 'test@email.com';
        con.AccountId = acc.Id;
        insert con;
        
        acc.Primary_Business_Contact__c= con.id;
        update acc;
        
        Territory_Coverage__C tc = new Territory_Coverage__C();
        tc.Zip_Code__c = '121008';
        insert tc;
        
        Account_Territory__c at = new Account_Territory__c();
        at.Account__c = acc.id;
        at.Territory_Coverage__c = tc.id;
        insert at;
        User u2 = new User(Alias = 'standt', Email=con.Email, 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standarduserrrrrr@testorg.com',IsActive =true,ContactId = con.id);
        insert u2;
        system.debug('u2--'+u2);

        
        Work_Order__c workOrdr = new Work_Order__c();
        workOrdr.Property_Zip_Code__c = '121008';
        workOrdr.Invoice_Notes_Options__c = 'Banding';
        insert workOrdr;
        
        Work_Order__c workOrdr2 = new Work_Order__c();
        workOrdr2.Property_Zip_Code__c = '121008';
        workOrdr2.Invoice_Notes_Options__c = 'Wear That Looks Like Soil';
        insert workOrdr2;
        
        Work_Order__c workOrdr3 = new Work_Order__c();
        workOrdr3.Property_Zip_Code__c = '121008';
        workOrdr3.Invoice_Notes_Options__c = 'Residual Urine Smell';
        insert workOrdr3;
        
        Work_Order__c workOrdr4 = new Work_Order__c();
        workOrdr4.Property_Zip_Code__c = '121008';
        workOrdr4.Invoice_Notes_Options__c = 'Pivot Wear';
        insert workOrdr4;
        
        Work_Order__c workOrdr5 = new Work_Order__c();
        workOrdr5.Property_Zip_Code__c = '121008';
        workOrdr5.Invoice_Notes_Options__c = 'Stain Magic';
        insert workOrdr5;
        
        Work_Order__c workOrdr6 = new Work_Order__c();
        workOrdr6.Property_Zip_Code__c = '121008';
        workOrdr6.Invoice_Notes_Options__c = 'High Levels Of Pet Hair';
        insert workOrdr6;
        
        ShareWorkOrder.manualshare(workOrdr);
        
        /*system.runAs(u){
            Work_Order__c workOrdr = new Work_Order__c();
            workOrdr.Property_Zip_Code__c = '121008';
            insert workOrdr;
        }*/
        
    }

}