force-app/main/default/objects/Account_Territory__c/Account_Territory__c.object-meta.xml
<CustomObject>
    <label>Account Territory</label>
    <nameField>
        <label>Account Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Territory__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Territories</relationshipLabel>
    <relationshipName>Account_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Territory__c/fields/Territory_Coverage__c.field-meta.xml
<CustomField>
    <fullName>Territory_Coverage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Territory Coverage</label>
    <referenceTo>Territory_Coverage__c</referenceTo>
    <relationshipLabel>Account Territories</relationshipLabel>
    <relationshipName>Account_Territories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Territory_Coverage__c/Territory_Coverage__c.object-meta.xml
<CustomObject>
    <label>Territory Coverage</label>
    <nameField>
        <label>Territory Coverage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territory Coverage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>Account_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Assigned_Business__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders (Assigned Business)</relationshipLabel>
    <relationshipName>Work_Orders_Business</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Assigned_Business_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Business_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Business User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Work_OrdersAssigned_Business</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Property_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Property_Zip_Code__c</fullName>
    <label>Property Zip Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ShareWorkOrder.cls
public class ShareWorkOrder {
        
    public static void manualshare(Work_Order__c workOrder){
        system.debug('order-'+workOrder);
        Territory_Coverage__C Coverage;
        Account businessAccount = new Account ();
        User AssignedUser = new User();
        id BusinesscontactId;
        List<Work_Order__share> totalSharings = new list<Work_Order__share> ();
        
        if(workOrder != null && workOrder.Property_Zip_Code__c != null){
            try{
                Coverage = [select id, (select id,Account__c, Account__r.Primary_Business_Contact__c from Account_Territories__r LIMIT 1) from Territory_Coverage__C where Zip_Code__C =:workOrder.Property_Zip_Code__c LIMIT 1];
                
            }catch(exception e){
                system.debug('error-'+e.getMessage());
            }
            system.debug('coverage--'+Coverage);
            if(Coverage != null){
                if(Coverage.Account_Territories__r != null && Coverage.Account_Territories__r.size()>0){
                    if(Coverage.Account_Territories__r[0].Account__c != null){
                        workOrder.Assigned_Business__c = Coverage.Account_Territories__r[0].Account__c;
                        if(Coverage.Account_Territories__r[0].Account__r.Primary_Business_Contact__c != null){
                            businessAccount = Coverage.Account_Territories__r[0].Account__r;
                            BusinesscontactId =Coverage.Account_Territories__r[0].Account__r.Primary_Business_Contact__c;
                        }  
                    }
                    else{
                         workOrder.Assigned_Business__c = null;
                    }
                }
            }
            else{
                workOrder.Assigned_Business__c = null;
            }
        }
        system.debug('BusinesscontactId'+BusinesscontactId);
        if(BusinesscontactId != null){
            try{
                AssignedUser = [select id, username from user where ContactId =:BusinesscontactId LIMIT 1];
            }catch(exception e){
                system.debug('error-'+e.getMessage());
            }
            
        }
        
        if(AssignedUser != null && AssignedUser.id !=null){
            system.debug('AssignedUser.id--'+AssignedUser.id);
            workOrder.Assigned_Business_User__c = AssignedUser.id;
            businessAccount.Assigned_Business_User__c = AssignedUser.id;
        }
        
        try{
            update workOrder;
            if(businessAccount.Assigned_Business_User__c != null){
            	update businessAccount;
            }
            system.debug('Successful--');
        }
        catch(dmlException e){
                system.debug('error-'+e.getMessage());
            }
        
        /*if(AssignedUser != null){
            Work_Order__share woshare;
                woshare = new Work_Order__share();
                woshare.ParentId = workOrder.id;
                woshare.UserOrGroupId = AssignedUser.id;
                woshare.AccessLevel = 'Read';
                system.debug('user--'+ AssignedUser.username+'ParentId--'+woshare.ParentId);
                totalSharings.add(woshare);
                if(Coverage.Account_Territories__r[0].Account__c != null){
                    woshare = new Work_Order__share();
                    woshare.ParentId = Coverage.Account_Territories__r[0].Account__c;
                    woshare.UserOrGroupId = AssignedUser.id;
                    woshare.AccessLevel = 'Read';
                    system.debug('user--'+ AssignedUser.username+'ParentId--'+woshare.ParentId); 
                }
                
                totalSharings.add(woshare);
        }
        if(totalSharings != null && totalSharings.size()>0){
            try{
                insert totalSharings;
                system.debug('Successful--'+totalSharings);
            }
            catch(Exception e){
                system.debug('error-'+e.getMessage());
            }
        }*/
    }
}