force-app/main/default/objects/SquareAPI__c/SquareAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SquareAPI</label>
</CustomObject>

force-app/main/default/objects/SquareAPI__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <label>ApplicationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SquareAPI__c/fields/EndpointURL__c.field-meta.xml
<CustomField>
    <fullName>EndpointURL__c</fullName>
    <label>EndpointURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Invoice_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Frequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <inlineHelpText>Name of person requesting the clean</inlineHelpText>
    <label>Requested By</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending IC</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending ICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Item__c/Work_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Stores services performed for a particular work order.</description>
    <label>Work Order Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Work Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Work Order Items</relationshipLabel>
    <relationshipName>Work_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestPaymentController.cls
@isTest
Public class TestPaymentController
{
    public static Work_Order__c workOrder{get;set;}
    public static void setupData(){
        SquareAPI__c squareAPI = new SquareAPI__c();
        squareAPI.ApplicationId__c = 'test';
        squareAPI.EndpointURL__c = 'https://connect.squareupsandbox.com/v2/payments';        
        squareAPI.Token__c = 'test';
        insert squareAPI;
        
        workOrder = new Work_Order__c();
        workOrder.Status__c = 'Pending';
        workOrder.Requested_By__c = 'Test';
        workOrder.Invoice_Frequency__c = 'Single';
        insert workOrder;
        
        Work_Order_Item__c workOrderItem = new Work_Order_Item__c();
        workOrderItem.Price__c = 1300;
        workOrderItem.Work_Order__c = workOrder.id;
        insert workOrderItem;
        
        ApexPages.currentPage().getParameters().put('id',workOrder.Id);
    }
    
    @isTest static void testMakePayment() {
        setupData();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Test.startTest();
               
        PaymentController obj = new PaymentController();
        obj.makePayment();
        Test.stopTest();
    }
    
    @isTest static void testMakePaymentError() {
        setupData();
        Test.setMock(HttpCalloutMock.class, new MockHttpeErrorResponseGenerator ());
        Test.startTest();
               
        PaymentController obj = new PaymentController();
        obj.makePayment();
        Test.stopTest();
    }
    
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"payment": {"id": "XFtuxZU1AKqSiMqlzESzJ7kat1BZY","created_at": "2020-07-23T17:56:36.296Z","updated_at": "2020-07-23T17:56:36.463Z","amount_money": {"amount": 1200,"currency": "USD"},"status": "COMPLETED","delay_duration": "PT168H","source_type": "CARD","card_details": {"status": "CAPTURED","card": {"card_brand": "VISA","last_4": "1111","exp_month": 11,"exp_year": 2022,"fingerprint": "sq-1-CLX6VYqy7Ad6SORZw7VdPMZUtU370yLA7wYBZC5yJpVERAAQiMMB7hdEkdha2ikEpg","card_type": "CREDIT","bin": "411111"},"entry_method": "KEYED","cvv_status": "CVV_ACCEPTED","avs_status": "AVS_ACCEPTED","statement_description": "SQ *DEFAULT TEST ACCOUNT"},"location_id": "LX2PH9SEARJQV","order_id": "zSGONuz8nt1vlWvr8sZaGtEIPkaZY","total_money": {"amount": 1200,"currency": "USD"},"receipt_number": "XFtu","receipt_url": "https://squareupsandbox.com/receipt/preview/XFtuxZU1AKqSiMqlzESzJ7kat1BZY","delay_action": "CANCEL","delayed_until": "2020-07-30T17:56:36.296Z"}}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    public class MockHttpeErrorResponseGenerator implements HttpCalloutMock {
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"errors": [{"code": "UNAUTHORIZED","detail": "test","category": "AUTHENTICATION_ERROR"}]}');
            res.setStatusCode(400);
            return res;
        }
    }
    
}