force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <description>Used to store information on the services that Smart Carpet Care provides</description>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Service_Description__c.field-meta.xml
<CustomField>
    <fullName>Service_Description__c</fullName>
    <label>Service Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Blacklight_Inspection__c.field-meta.xml
<CustomField>
    <fullName>Blacklight_Inspection__c</fullName>
    <label>Blacklight Inspection</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blacklight Inspection with Full Report + Photos</fullName>
            </value>
            <value>
                <fullName>Blacklight Inspection with Brief Report</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <inlineHelpText>If you have a % that does not appear in the drop down list, select custom at the bottom and then fill in the Discount % field with the percentage you want to apply.</inlineHelpText>
    <label>Discount</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5% Discount</fullName>
            </value>
            <value>
                <fullName>First Time Customer 10% Discount</fullName>
            </value>
            <value>
                <fullName>Preferred Customer 10% Discount</fullName>
            </value>
            <value>
                <fullName>Special Appreciation 25% Discount</fullName>
            </value>
            <value>
                <fullName>Golden Customer 50% Discount</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Discount_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Discount_Percentage__c</fullName>
    <inlineHelpText>Use this field only when you have selected &quot;Custom&quot; in Discount field above.  Then put in the % that you want to apply.</inlineHelpText>
    <label>Discount %</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Field_Crew_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Field_Crew_End_Time__c</fullName>
    <inlineHelpText>Auto populated field that captures the time field crew worker clocked out at job</inlineHelpText>
    <label>Field Crew End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Field_Crew_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Field_Crew_Start_Time__c</fullName>
    <inlineHelpText>Auto populated field that captures the time field crew worker clocked in at job</inlineHelpText>
    <label>Field Crew Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Invoice_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Frequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Invoice_Notes__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Notes__c</fullName>
    <inlineHelpText>Pulls options selected from Invoice Notes Options</inlineHelpText>
    <label>Invoice Auto Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Invoice_Notes_Options__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Notes_Options__c</fullName>
    <label>Invoice Notes Options</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Carpet Roll</fullName>
            </value>
            <value>
                <fullName>Wear That Looks Like Soil</fullName>
            </value>
            <value>
                <fullName>Banding</fullName>
            </value>
            <value>
                <fullName>Bleaching</fullName>
            </value>
            <value>
                <fullName>Pivot Wear</fullName>
            </value>
            <value>
                <fullName>Residual Urine Smell</fullName>
            </value>
            <value>
                <fullName>Stain Magic</fullName>
            </value>
            <value>
                <fullName>High Levels Of Pet Hair</fullName>
            </value>
            <value>
                <fullName>Carpet Illusions After Cleaning</fullName>
            </value>
            <value>
                <fullName>Furniture Divots</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <inlineHelpText>Name of person requesting the clean</inlineHelpText>
    <label>Requested By</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Earliest date to clean carpet</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending IC</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending ICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Van_assignment__c.field-meta.xml
<CustomField>
    <fullName>Van_assignment__c</fullName>
    <label>Van assignment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Van 1</fullName>
                <color>#FFFF66</color>
                <label>Van 1</label>
            </value>
            <value>
                <fullName>Van 2</fullName>
                <color>#CC33CC</color>
                <label>Van 2</label>
            </value>
            <value>
                <fullName>Van 3</fullName>
                <color>#3333FF</color>
                <label>Van 3</label>
            </value>
            <value>
                <fullName>Van 4</fullName>
                <color>#33CC00</color>
                <label>Van 4</label>
            </value>
            <value>
                <fullName>Van 5</fullName>
                <color>#66FF99</color>
                <default>true</default>
                <label>Van 5</label>
            </value>
            <value>
                <fullName>Team Van</fullName>
                <color>#FF9900</color>
                <label>Team Van</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Item__c/Work_Order_Item__c.object-meta.xml
<CustomObject>
    <description>Stores services performed for a particular work order.</description>
    <label>Work Order Item</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Work Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order_Item__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Service must be active to appear in list</errorMessage>
        <filterItems>
            <field>Service__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Work Order Items</relationshipLabel>
    <relationshipName>Work_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order_Item__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Work Order Items</relationshipLabel>
    <relationshipName>Work_Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CreateInvoiceControllerTest.cls
@isTest
public class CreateInvoiceControllerTest {
    static testMethod void Invoice(){
        User u = [select id, name, email from User where Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];
        account acc = new account();
        acc.name = 'test account';
        insert acc;
        EmailTemplate et = [select id,Name from EmailTemplate where Name = 'Interval Cleaning Contract'];
        contact con = new contact();
        con.LastName = 'Kumarr technologies invoice';
        con.Email = 'test@email.com';
        con.AccountId = acc.Id;
        insert con;
        
        Work_Order__c work;
        work = new Work_Order__c();
        work.Van_assignment__c = 'Van5';
        work.Account_Name__c = acc.Id;
        work.Requested_By__c = 'Test';
        String val = 'Bleaching;Carpet Roll;Banding;Wear That Looks Like Soil;Pivot Wear;Residual Urine Smell;Stain Magic;';
        work.Invoice_Notes_Options__c = val;
        work.Invoice_Notes__c = 'My Invoice Notes';
        work.Start_Date__c = system.today();
        work.Status__c = 'Completed';
        work.OwnerId = UserInfo.getUserId();
        work.Field_Crew_End_Time__c = system.today()-1;
        work.Field_Crew_Start_Time__c = system.today();
        work.Invoice_Frequency__c = 'Monthly';  
        work.Discount__c='Custom';  
        work.Discount_Percentage__c = 10;   
        insert work;    
            
        Service__c serv = new Service__c(); 
        serv.Active__c = true;  
        serv.Service_Description__c = 'Description';    
        serv.Price__c = 123;    
        serv.name = 'test'; 
        insert serv;    
            
        Work_Order_Item__c item = new Work_Order_Item__c(); 
        item.Work_Order__c = work.id;   
        item.Service__c = serv.id;  
        item.Comment__c = 'comm';   
        item.Price__c = 200;    
        insert item;    
            
        ContentVersion contentVersionInsert = new ContentVersion(Title = 'Test',PathOnClient = 'Test.jpg',  
                                                                 VersionData = Blob.valueOf('Test Content Data'),   
                                                                 IsMajorVersion = true);    
        insert contentVersionInsert;    
            
        // Test INSERT  
        ContentVersion contentVersionSelect = [SELECT Id, Title, ContentDocumentId FROM ContentVersion  
                                               WHERE Id = :contentVersionInsert.Id LIMIT 1];    
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];    
        System.assertEquals(documents.size(), 1);
        List <string> ids = new list<string>();
        ids.add(item.id);
        string jsonIds = JSON.serialize(ids);
        ApexPages.currentPage().getParameters().put('woiIdJson', jsonIds);
        ApexPages.currentPage().getParameters().put('id', work.id); 
        //ApexPages.currentPage().getParameters().put('woItem', item.id);   
        ApexPages.StandardController sc = new ApexPages.StandardController(work);   
        CreateInvoiceController invoice1 = new CreateInvoiceController(sc); 
            
        system.runAs(u){
            invoice1.attachment = true;
            invoice1.saveAttachement();
            CreateInvoiceController invoice = new CreateInvoiceController();
            invoice1.attachment = true;
            invoice1.LoggedInUserEmail = u.email;
            invoice1.getContacts();
            invoice1.getTemplates();
            invoice1.onChangeTemplate();
            invoice1.getEmailTemplates();
            invoice1.selectedEmailTemplate = et.Id;
            invoice1.onChangeRadio();
            invoice1.cancel();
            work.Status__c = 'Invoice Paid';
            update work;
            invoice1.getTemplates();
            //invoice1.initialised = false;
            invoice1.selectedTemplate = 'Smart Invoice with BL Report';
            invoice1.selectedMethod = 'Attach';
            invoice1.onChangeRadio();
            invoice1.onChangeTemplate();
            invoice1.getContentDis();
            
            invoice1.getOrgwideAddress();
            invoice1.cancelForCommunity();
            invoice1.templateId= et.id;
            invoice1.prepareEmail(); 
            invoice1.onChangePrepareEmail();
            //invoice1.prepareEmail();
            //invoice1.sendInvoiceEmail();
        }
        
    }
    
    static testMethod void Invoice1(){
        account acc = new account();
        acc.name = 'Sailfin test account';
        insert acc;
        contact con = new contact();
        con.LastName = 'sailfin technologies invoice';
        con.Email = 'test@email.com';
        con.AccountId = acc.Id;
        insert con;
        
        Work_Order__c work;
        work = new Work_Order__c();
        work.Account_Name__c = acc.Id;
        work.Van_assignment__c = 'Van5'; 
        work.Requested_By__c = 'Test';
        work.Start_Date__c = system.today();
        work.Status__c = 'Invoice Paid';
        work.OwnerId = UserInfo.getUserId();
        work.Field_Crew_End_Time__c = system.today()-1;
        work.Field_Crew_Start_Time__c = system.today();
         work.Invoice_Frequency__c = 'Single';  
        insert work;    
            
        Service__c serv = new Service__c(); 
        serv.Active__c = true;  
        serv.Service_Description__c = 'Description';    
        serv.Price__c = 123;    
        insert serv;    
            
        Work_Order_Item__c item = new Work_Order_Item__c(); 
        item.Work_Order__c = work.id;   
        item.Service__c = serv.id;  
        insert item;    
            
        ApexPages.currentPage().getParameters().put('woItem', 'null');  
        ApexPages.currentPage().getParameters().put('id', work.id); 
        ApexPages.StandardController sc = new ApexPages.StandardController(work);   
        CreateInvoiceController invoice1 = new CreateInvoiceController(sc); 
            
        //CreateInvoiceController invoice = new CreateInvoiceController();  
        //invoice1.attachment = true;   
        invoice1.getContentDis();
        invoice1.getContacts();
        invoice1.getTemplates();
        invoice1.onChangeTemplate();
        invoice1.onChangeRadio();
        invoice1.cancel();
        invoice1.getTemplates();
        //invoice1.initialised = true;
        invoice1.selectedTemplate = 'Work Order Invoice Paid';
        invoice1.selectedMethod = 'Email';
        invoice1.onChangeRadio();
        invoice1.onChangeTemplate();
        invoice1.saveAttachement();
        
    }
    
    static testMethod void Invoice2(){
        Work_Order__c work;
        work = new Work_Order__c();
        work.Van_assignment__c = 'Van5'; 
        work.Requested_By__c = 'Test';
        work.Start_Date__c = system.today();
        work.Status__c = 'Invoice Paid';
        work.Blacklight_Inspection__c = 'Blacklight Inspection with Brief Report';
        work.OwnerId = UserInfo.getUserId();
        work.Field_Crew_End_Time__c = system.today()-1;
        work.Field_Crew_Start_Time__c = system.today();
        insert work;
        
        Service__c serv = new Service__c();
        serv.Active__c = true;
        serv.Service_Description__c = 'Description';
        serv.Price__c = 123;
        insert serv;
        
        Work_Order_Item__c item = new Work_Order_Item__c();
        item.Work_Order__c = work.id;
        item.Service__c = serv.id;
        insert item;
        
        ApexPages.currentPage().getParameters().put('id', work.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(work);
        CreateInvoiceController invoice1 = new CreateInvoiceController(sc);
        
        //CreateInvoiceController invoice = new CreateInvoiceController();
        invoice1.attachment = true;
        invoice1.getContacts();
        invoice1.getTemplates();
        invoice1.onChangeTemplate();
        invoice1.onChangeRadio();
        invoice1.cancel();
        invoice1.getTemplates();
        invoice1.initialised = false;
        invoice1.selectedTemplate = 'Work Order Invoice Paid';
        invoice1.selectedMethod = 'Attach';
        invoice1.onChangeRadio();
        invoice1.onChangeTemplate();
        invoice1.saveAttachement();
        
    }
}