force-app/main/default/objects/Purchase_Order_Lines__c/Purchase_Order_Lines__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Lines</label>
    <nameField>
        <displayFormat>POL-{0000}</displayFormat>
        <label>Purchase Order Lines #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Act_Cost__c.field-meta.xml
<CustomField>
    <fullName>Act_Cost__c</fullName>
    <label>Actual Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Purchase_Orders__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Orders__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Orders__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Shipping_Handling__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Handling__c</fullName>
    <label>Shipping/Handling</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Sub_Total__c.field-meta.xml
<CustomField>
    <fullName>Sub_Total__c</fullName>
    <formula>Act_Cost__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sub-Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Total_Price_Formula__c.field-meta.xml
<CustomField>
    <fullName>Total_Price_Formula__c</fullName>
    <formula>Sub_Total__c - Discount_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/Purchase_Orders__c.object-meta.xml
<CustomObject>
    <label>Purchase Orders</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Orders__c/fields/Account_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Address__c</fullName>
    <formula>Account_Name__r.ShippingStreet + BR() + 
Account_Name__r.ShippingCity + &quot;, &quot;+ 
Account_Name__r.ShippingState +&quot; &quot; + 
Account_Name__r.ShippingPostalCode + BR() + 
Account_Name__r.ShippingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Party responsible for payment</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Balance_Due__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due__c</fullName>
    <formula>(Subtotal__c  +  Tax_Amount__c  +  Shipping_Handling__c) -  Discount_Credit__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Discount_Credit__c.field-meta.xml
<CustomField>
    <fullName>Discount_Credit__c</fullName>
    <label>Discount/Credit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>Franchise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Franchise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders (Franchise)</relationshipLabel>
    <relationshipName>Purchase_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Franchise_Address__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Address__c</fullName>
    <formula>Franchise__r.ShippingStreet + BR() +
Franchise__r.ShippingCity + &quot;, &quot;+
Franchise__r.ShippingState +&quot; &quot; +
Franchise__r.ShippingPostalCode + BR() +
Franchise__r.ShippingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Franchise Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Franchise_Billing_Address__c.field-meta.xml
<CustomField>
    <fullName>Franchise_Billing_Address__c</fullName>
    <formula>Franchise__r.BillingStreet + BR() +
 Franchise__r.BillingCity +&quot; &quot;+
 Franchise__r.BillingState+&quot; &quot;+
 Franchise__r.BillingPostalCode +BR()+
 Franchise__r.BillingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Franchise Billing Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Inbound_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inbound Purchase Order</label>
    <referenceTo>Purchase_Orders__c</referenceTo>
    <relationshipLabel>Outbound Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
                <default>true</default>
                <label>ACH</label>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/PO_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Date__c</fullName>
    <label>PO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Ship_Via__c.field-meta.xml
<CustomField>
    <fullName>Ship_Via__c</fullName>
    <label>Ship Via</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <label>Shipping Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Shipping_Handling__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Handling__c</fullName>
    <label>Shipping/Handling</label>
    <summarizedField>Purchase_Order_Lines__c.Shipping_Handling__c</summarizedField>
    <summaryForeignKey>Purchase_Order_Lines__c.Purchase_Orders__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Order Created</fullName>
            </value>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Order Shipped</fullName>
            </value>
            <value>
                <fullName>Order Completed</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <summarizedField>Purchase_Order_Lines__c.Total_Price_Formula__c</summarizedField>
    <summaryForeignKey>Purchase_Order_Lines__c.Purchase_Orders__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Tax_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_Amount__c</fullName>
    <formula>(Tax__c  *  Subtotal__c ) / 100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tax Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Outbound = Orders for Smart Supply Inventory. Inbound = Orders received from franchise owners</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/POInvoiceController.cls
public class POInvoiceController{
    public List<Purchase_Orders__c> poList{get;set;}
    public List<Purchase_Order_Lines__c> poLinesList{get;set;}
    public Decimal Total{get;set;}
    public String poId{get;set;}
    public String selectedTemplate{get;set;}
    public List<Contact> cList{get;set;}
    public Boolean attachment{get;set;}
    public String selectedMethod{get;set;}
    public String dateTimeValue { get; set; }
    public String dueDate { get; set; }
    
    /*Boolean value to Display */
    public Boolean franchiseBillingAddExists {get;set;}
    
    Private Purchase_Orders__c pageOpp;
    public Boolean initialised{get; set;}
    Date myDate = system.today();
    public List<SelectOption> selectedContacts{get;set;}
    
    public POInvoiceController(ApexPages.StandardController stdController) {
        this.pageOpp = (Purchase_Orders__c)stdController.getRecord();
        poId = ApexPages.currentPage().getParameters().get('id');
        initialised=false;
        selectedMethod = 'Email';
        poList = [select id,Status__c,Type__c ,Ship_Via__c,Name,Account_Name__c,Account_Name__r.Name,Account_Address__c,Shipping_Address__c,Franchise__c,Franchise_Address__c, CreatedDate,Payment_Terms__c,Franchise_Billing_Address__c
        from Purchase_Orders__c where id =: poId];
        
        if(poList != null &&  poList.size()>0){
            
            cList = [select id,Name,AccountId from Contact where AccountId =: poList[0].Account_Name__c];
        }
        selectedContacts = new List<SelectOption>();
        if(cList != null && cList.size()>0){
            for(Contact c : cList){
                if(c.Name.containsIgnoreCase('invoice')){
                    selectedContacts.add(new SelectOption(c.id,c.Name));
                }
            }    
        }          
    }
    
    public POInvoiceController(){
        Total = 0;
        poId = ApexPages.currentPage().getParameters().get('id');
        poList = [select id,PO_Date__c,Status__c,Type__c,Ship_Via__c,Name,Account_Name__c,Account_Name__r.Name,Account_Address__c,Shipping_Address__c,Franchise__c,Franchise_Address__c,CreatedDate,Payment_Terms__c,
                  Subtotal__c,Tax_Amount__c,Shipping_Handling__c,Balance_Due__c,Discount_Credit__c,Franchise_Billing_Address__c
                  from Purchase_Orders__c where id =: poId];
        
        dateTimeValue = System.Now().format('MM/dd/yy hh:mm a', 'America/Denver');//GMT
        	/*Initalize franchiseBillingAddExists value as false*/
        	this.franchiseBillingAddExists=False;
            /*Franchise Billing Address Exists*/
            if(poList[0].Franchise_Billing_Address__c!='<br>  <br>'){
               this.franchiseBillingAddExists=True;
                
            }
        if(poList[0].PO_Date__c != null){
            Date d = poList[0].PO_Date__c +  15;
            DateTime dt = DateTime.newInstance(d.year(),d.month(),d.day());
    
            dueDate = dt.format('MM/dd/yy', 'America/Denver');//GMT
        }
        
        poLinesList = [select id,Total_Price_Formula__c,Product__c,Product__r.ProductCode,Product__r.Name,Product__r.Description,Quantity__c,Act_Cost__c,Sub_Total__c,
        Purchase_Orders__c,Purchase_Orders__r.Balance_Due__c from Purchase_Order_Lines__c where Purchase_Orders__c =: poId];  
        
        for(Purchase_Order_Lines__c pol : poLinesList){
            Total = Total + pol.Purchase_Orders__r.Balance_Due__c;
        }                      
    }
    
    public List<SelectOption> getContacts(){
    List<SelectOption> options = new List<SelectOption>();
    
    if(cList != null && cList.size()>0){
        for(Contact c : cList){
            if(!c.Name.containsIgnoreCase('invoice')){
                options.add(new SelectOption(c.id,c.Name));
            }    
        }
    }
    return options;
    }
    
    public List<SelectOption> getTemplates(){
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('None','None'));
        if(poList != null && poList.size()>0){
            if(poList[0].Status__c == 'Order Placed'||poList[0].Status__c == 'Order Shipped'||poList[0].Status__c == 'Invoiced'){ 
                options.add(new SelectOption('Purchase Order Invoice','Purchase Order Invoice'));
            }else if(poList[0].Status__c == 'Order Completed'){
                options.add(new SelectOption('Purchase Order Invoice Paid','Purchase Order Invoice Paid'));
            }
        }
        return options;
    }
    
    public PageReference saveAttachement(){
        if(selectedTemplate == 'None'){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select the Template to proceed!!'));
            return null;
        }
        
        String emailaddress = '';
        
        Set<String> selConId = new Set<String>();
        for(SelectOption s : selectedContacts){
            selConId.add(s.getValue());    
        }
        
        List<Contact> con = new List<Contact>();
        if(selConId != null && selConId.size()>0){
            con = [select id,email from Contact where Id IN: selConId];
        }
        
        List<Contact> tempList = new List<Contact>();
        for(Integer i =1;i<con.size();i++){
            tempList.add(con[i]);
        }        
        for(Contact c : tempList){
            emailaddress = emailaddress + c.Email + ',';
        }
        
        PageReference pageRef;
        
        if (!initialised && pageOpp.ID !=NULL) {
            PageReference pdf;
            if(selectedTemplate == 'Purchase Order Invoice'||selectedTemplate == 'Purchase Order Invoice Paid'){
                pdf = new PageReference ('/apex/PO_Invoice_Template?id='+pageOpp.Id);
            }
            Blob body;
            try{
                if(pdf != null)
                body = pdf.getContentAsPDF();
            }catch (VisualforceException e) {
                body = Blob.valueOf('No file');
            }
            
            if(attachment == true){
                Attachment attach = new Attachment();
                attach.Body = body;
                if(selectedTemplate == 'Purchase Order Invoice' || selectedTemplate == 'Purchase Order Invoice Paid'){
                    attach.Name = 'Invoice for' + poList[0].name +'.pdf';
                }
                attach.IsPrivate = false;
                attach.ParentId = pageOpp.Id;
                insert attach;
            }
            
            ContentVersion version = new ContentVersion();
            if(selectedTemplate == 'Purchase Order Invoice' || selectedTemplate == 'Purchase Order Invoice Paid'){
                version.Title='Invoice for' + poList[0].name +'.pdf';
                version.PathOnClient = 'Invoice for' + poList[0].name +'.pdf';
            }
            version.VersionData = body;
            insert version;
            
            FeedItem post = new FeedITem();
            if(selectedTemplate == 'Purchase Order Invoice' || selectedTemplate == 'Purchase Order Invoice Paid'){
                post.body = 'Invoice sent to Account for this Purchase Order';
            }
            post.ParentID = pageOpp.Id;
            insert post;
            
            FeedAttachment postAttachment = new FeedAttachment();
            postAttachment.FeedEntityId = post.id;
            postAttachment.Type = 'Content';
            postAttachment.RecordId = version.id;
            insert postAttachment;
            
            if(selectedMethod == 'Email'){
                Document document = new Document();
                document.AuthorId = UserInfo.getUserId();
                document.FolderId = UserInfo.getUserId(); // put it in running user's folder
                document.Body = body;
                if(selectedTemplate == 'Purchase Order Invoice' || selectedTemplate == 'Purchase Order Invoice Paid'){
                    document.Name = 'Invoice for' + poList[0].name +'.pdf';
                }
                insert document;
                
                String sscAddress = 'smartaccountmgmt@smartcarpetcare.com';
                String templName='';
                if(poList[0].Status__c=='Order Completed'){
                    templName='Purchase Order Invoice Paid';
                }
                else if(poList[0].Status__c == 'Order Placed'||poList[0].Status__c == 'Order Shipped'||poList[0].Status__c == 'Invoiced'){
                    templName='Purchase Order Invoice';
                }
                system.debug(templName);
                system.debug(poId);
                if(templName!=null && templName!=''){
                 	EmailTemplate emailTemplate =[Select Id from EmailTemplate WHERE name=:templName];  
                	pageRef = new PageReference('/_ui/core/email/author/EmailAuthor?retURL=/'+ poId + '&p2_lkid=' + con[0].id + '&p24=' + emailaddress + '&p5=' + sscAddress +'&saveURL=%2F' + poId +'&p3_lkid=' +poId+'&doc_id=' + document.id+'&template_id='+emailTemplate.id);
                }
                 
                
            }
            else{
                pageRef = new PageReference('/'+poId);
            }
            initialised=true;
        }
        else{
            pageRef = new PageReference('/'+poId);
        }
        return pageRef;
    }
    
    public PageReference Cancel(){
        PageReference pageRef = new PageReference('/'+poId);
        return pageRef;
    }

}