force-app/main/default/objects/Purchase_Order_Lines__c/Purchase_Order_Lines__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Lines</label>
    <nameField>
        <displayFormat>POL-{0000}</displayFormat>
        <label>Purchase Order Lines #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Purchase_Orders__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Orders__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Orders__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/Purchase_Orders__c.object-meta.xml
<CustomObject>
    <label>Purchase Orders</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Orders__c/fields/Franchise__c.field-meta.xml
<CustomField>
    <fullName>Franchise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Franchise</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders (Franchise)</relationshipLabel>
    <relationshipName>Purchase_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Inbound_Purchase_Order__c.field-meta.xml
<CustomField>
    <fullName>Inbound_Purchase_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Inbound Purchase Order</label>
    <referenceTo>Purchase_Orders__c</referenceTo>
    <relationshipLabel>Outbound Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Outbound = Orders for Smart Supply Inventory. Inbound = Orders received from franchise owners</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PurchaseOrderTriggerHandler.cls
public class PurchaseOrderTriggerHandler {
    public static void handleShippingAddress(List<Purchase_Orders__c> newPurchaseOrders) {
        List<Purchase_Orders__c> inboundPurchaseOrders = new List<Purchase_Orders__c>();
        
        for(Purchase_Orders__c po: newPurchaseOrders) {
            if(po.Type__c == 'Inbound') {
                User u = [SELECT Id, AccountId FROM User WHERE Id =: UserInfo.getUserId()];
                po.Franchise__c = u.AccountId;
            }
        }
    }
    
    public static void handleEmptyInboundPurchaseOrderDeletion(List<Purchase_Orders__c> updatedPurchaseOrders) {
        Set<Id> poIds = new Set<Id>();
        for(Purchase_Orders__c po: updatedPurchaseOrders) {
            if(po.Type__c == 'Outbound') {
                poIds.add(po.Inbound_Purchase_Order__c);
            }
        }
        List<Purchase_Orders__c> inboundOrdersWithEmptyPOLines = [SELECT Id from Purchase_Orders__c
                                                                  where Id IN: poIds 
                                                                  and Type__c = 'Inbound' 
                                                                  and Id not in (select Purchase_Orders__c from Purchase_order_Lines__c)];
        
        try {
            delete inboundOrdersWithEmptyPOLines;
        } catch(DmlException ex){
            system.debug('Error occured while deleting empty inbound PO - ' + ex.getMessage());
        } 
    }
}