force-app/main/default/objects/Purchase_Order_Lines__c/Purchase_Order_Lines__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Lines</label>
    <nameField>
        <displayFormat>POL-{0000}</displayFormat>
        <label>Purchase Order Lines #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Act_Cost__c.field-meta.xml
<CustomField>
    <fullName>Act_Cost__c</fullName>
    <label>Actual Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item #</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <formula>Product__r.List_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Parent_Product__c.field-meta.xml
<CustomField>
    <fullName>Parent_Product__c</fullName>
    <formula>Product__r.Parent_Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Parent Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Product__r.Product_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Purchase_Orders__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Orders__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Orders__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/Purchase_Orders__c.object-meta.xml
<CustomObject>
    <label>Purchase Orders</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Orders__c/fields/Account_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Address__c</fullName>
    <formula>Account_Name__r.ShippingStreet + BR() + 
Account_Name__r.ShippingCity + &quot;, &quot;+ 
Account_Name__r.ShippingState +&quot; &quot; + 
Account_Name__r.ShippingPostalCode + BR() + 
Account_Name__r.ShippingCountry</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Party responsible for payment</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Order Shipped</fullName>
            </value>
            <value>
                <fullName>Order Completed</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
                <default>true</default>
                <label>ACH</label>
            </value>
            <value>
                <fullName>Net 30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/PO_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Date__c</fullName>
    <label>PO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Ship_Via__c.field-meta.xml
<CustomField>
    <fullName>Ship_Via__c</fullName>
    <label>Ship Via</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Address__c</fullName>
    <label>Shipping Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Order Created</fullName>
            </value>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Order Shipped</fullName>
            </value>
            <value>
                <fullName>Order Completed</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Supplier_Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Supplier_Manufacturer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supplier/Manufacturer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders (Supplier/Manufacturer)</relationshipLabel>
    <relationshipName>Purchase_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Outbound = Orders for Smart Supply Inventory. Inbound = Orders received from franchise owners</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddPOLines.cls
public class AddPOLines{
    public Purchase_Orders__c poObj{get;set;}
    public String UserType{get; set;}
    public List<Product2> productList{get;set;}
    public List<productwrapper> wrapperList{get;set;}
    public productwrapper wrapObj{get;set;}
    List<Product2> selectedProducts = new List<Product2>();
    
    List<Purchase_Order_Lines__c> pols {get;set;}
    Map<Id,Purchase_Order_Lines__c> productMap{get;set;}
    List<Purchase_Order_Lines__c> poLinesList;
   
    public String poId{get;set;}
    
    public AddPOLines(){
        poId = ApexPages.currentPage().getParameters().get('id');
        UserType = userinfo.getusertype();
        wrapperList = new List<productwrapper>();
        poLinesList = new List<Purchase_Order_Lines__c>();
  
        poObj = [select id,Status__c,Order_Status__c,Type__c ,PO_Date__c,Ship_Via__c,Name,Account_Name__c,Account_Name__r.Name,Account_Address__c,Shipping_Address__c,CreatedDate,Payment_Terms__c
                from Purchase_Orders__c where id =: poId];
                
        if(poObj != null){
            pols = [select id,Quantity__c,Product__c from Purchase_Order_Lines__c where Purchase_Orders__c =: poId];
            
            productMap = new Map<Id,Purchase_Order_Lines__c>();
            
            for(Purchase_Order_Lines__c pol : pols){
                productMap.put(pol.Product__c,pol);
            }    
            
            List<Product2> trueproducts = [select id,ProductCode,Name,Description,List_Price__c,Parent_Product__c,Product_Type__c,Smart_Supply_Maintained_Inventory__c,Supplier_Manufacturer__c
                                           from Product2 where Id IN: productMap.keyset()];   
            
            if(trueproducts != null && trueproducts.size()>0){
                for(Product2 pro : trueproducts){
                    wrapObj = new productwrapper();
                    wrapObj.p = new Product2();
                    wrapObj.p = pro;
                    wrapObj.Quantity = productMap.get(pro.id).Quantity__c;
                    wrapObj.selected = true;
                    wrapperList.add(wrapObj);
                }
            }  
            
            productList = [select id,ProductCode,Name,Description,List_Price__c,Parent_Product__c,Product_Type__c,Smart_Supply_Maintained_Inventory__c,Supplier_Manufacturer__c from Product2 where Id NOT IN: productMap.keyset() order by Smart_Supply_Maintained_Inventory__c DESC ];
            
            if(productList != null && productList.size()>0){
                for(Product2 pro : productList){
                    wrapObj = new productwrapper();
                    wrapObj.p = new Product2();
                    wrapObj.p = pro;
                    wrapObj.Quantity = 0;
                    wrapObj.selected = false;
                    wrapperList.add(wrapObj);
                }
            } 
        }   
        
        if(poObj != null && poObj.Status__c == 'Order Placed'){
            Apexpages.addMessage(new Apexpages.Message(ApexPages.severity.INFO, 'Your order has been placed.You can not edit or add more Line Items!!'));
        }
    }
    
    public void Save(){
    
        delete pols;
        Integer row = 1;
        
        for(productwrapper pwrapper : wrapperList){
           if(pwrapper.selected == true){
               Purchase_Order_Lines__c pol = new Purchase_Order_Lines__c();
               pol.Item__c = row++;
               pol.Purchase_Orders__c = poId;
               pol.Product__c = pwrapper.p.id;
               pol.Act_Cost__c = pwrapper.p.List_Price__c;
               pol.Quantity__c = pwrapper.Quantity;
               poLinesList.add(pol); 
           } 
        }
          
            poObj.Status__c = 'Pending';
            update poObj;
            
            insert poLinesList;
    }
 
    public Pagereference Submit(){
       delete pols;
       Integer row = 1;
        
        for(productwrapper pwrapper : wrapperList){
           if(pwrapper.selected == true && pwrapper.Quantity > 0){
               Purchase_Order_Lines__c pol = new Purchase_Order_Lines__c();
               pol.Item__c = row++;
               pol.Purchase_Orders__c = poId;
               pol.Product__c = pwrapper.p.id;
               pol.Act_Cost__c = pwrapper.p.List_Price__c;
               pol.Quantity__c = pwrapper.Quantity;
               poLinesList.add(pol); 
           } 
        }
        
        poObj.Status__c = 'Order Placed';
        poObj.PO_Date__c = System.Today();
        update poObj;
        
        insert poLinesList;
        
        return new PageReference('/'+poId);
    }
    
    public Pagereference Cancel(){
        return new PageReference('/'+poId);
    }
    
    public class productwrapper{
        public Product2 p{get; set;}
        public Boolean selected {get; set;}
        public Decimal Quantity {get;set;}
        
        public productwrapper(){
            
        }
    }

}