force-app/main/default/objects/Purchase_Order_Lines__c/Purchase_Order_Lines__c.object-meta.xml
<CustomObject>
    <label>Purchase Order Lines</label>
    <nameField>
        <displayFormat>POL-{0000}</displayFormat>
        <label>Purchase Order Lines #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Order Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Order_Lines__c/fields/Purchase_Orders__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Orders__c</fullName>
    <label>Purchase Order</label>
    <referenceTo>Purchase_Orders__c</referenceTo>
    <relationshipLabel>Purchase Order Lines</relationshipLabel>
    <relationshipName>Purchase_Order_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/Purchase_Orders__c.object-meta.xml
<CustomObject>
    <label>Purchase Orders</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>Purchase Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Orders__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Party responsible for payment</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Order Created</fullName>
            </value>
            <value>
                <fullName>Order Placed</fullName>
            </value>
            <value>
                <fullName>Order Shipped</fullName>
            </value>
            <value>
                <fullName>Order Completed</fullName>
            </value>
            <value>
                <fullName>Order Cancelled</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Back Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Purchase_Orders__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Outbound = Orders for Smart Supply Inventory. Inbound = Orders received from franchise owners</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbound</fullName>
                <default>true</default>
                <label>Inbound</label>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/POInvoiceControllerTest.cls
@isTest
public class POInvoiceControllerTest {
    static testMethod void POInvoice(){
        Account a = new Account(Name='Smart Supply Co LLC - Franchise Community');
        insert a;
        
        Purchase_Orders__c po = new Purchase_Orders__c();
        po.Account_Name__c = a.id;
        po.Type__c = 'Inbound';
        po.Status__c = 'Order Completed';
        insert po;
        
        Contact c = new Contact(AccountId = a.id,LastName = 'Test Contact');
        insert c;
        
        Product2 prod = new Product2(Name = 'Laptop X200', Available_Quantity__c = 10,
        Family = 'Hardware');
        insert prod;
        
        Purchase_Order_Lines__c pol = new Purchase_Order_Lines__c();
        pol.Purchase_Orders__c = po.id;
        pol.Description__c = 'Description';
        pol.Product__c = prod.id;
        pol.Quantity__c = 1;
        insert pol;
        
        ApexPages.currentPage().getParameters().put('id', po.id);
        ApexPages.StandardController sc = new ApexPages.StandardController(po);
        POInvoiceController poinv = new POInvoiceController(sc);
        
        POInvoiceController invoice = new POInvoiceController();
        poinv.selectedContacts.add(new SelectOption(c.id,c.LastName));
        poinv.getContacts();
        poinv.getTemplates();
        poinv.attachment = true;
        poinv.selectedTemplate = 'Purchase Order Invoice';
        poinv.selectedMethod = 'Email';
        poinv.saveAttachement();
        poinv.Cancel();
    }    

}