force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending IC</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending ICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Van_assignment__c.field-meta.xml
<CustomField>
    <fullName>Van_assignment__c</fullName>
    <label>Van assignment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Van 1</fullName>
                <color>#FFFF66</color>
                <label>Van 1</label>
            </value>
            <value>
                <fullName>Van 2</fullName>
                <color>#CC33CC</color>
                <label>Van 2</label>
            </value>
            <value>
                <fullName>Van 3</fullName>
                <color>#3333FF</color>
                <label>Van 3</label>
            </value>
            <value>
                <fullName>Van 4</fullName>
                <color>#33CC00</color>
                <label>Van 4</label>
            </value>
            <value>
                <fullName>Van 5</fullName>
                <color>#66FF99</color>
                <default>true</default>
                <label>Van 5</label>
            </value>
            <value>
                <fullName>Team Van</fullName>
                <color>#FF9900</color>
                <label>Team Van</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <label>Commercial</label>
</RecordType>

force-app/main/default/objects/Work_Order__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <label>Residential</label>
</RecordType>

force-app/main/default/classes/superCloneController.cls
global class superCloneController {
    public Work_Order__c sourceWorkOrder { get; set; }
    public Work_Order__c targetWorkOrder { get; set; }
    public ID workOrderID {get;set;}
    /*public superCloneController(){
        workOrderID = ApexPages.currentPage().getParameters().get('id');
        workOrderID= String.valueOf(workOrderID).substring(0, 15);
        //cloneRecord(woId);
    }
    */
    public superCloneController(ApexPages.StandardController stdController){
        workOrderID = ((Work_Order__c)stdController.getRecord()).id;
        workOrderID= String.valueOf(workOrderID).substring(0, 15);
    }
    
    public PageReference cloneRecord(){
        system.debug('inside cloneRecord');
        try{
            workOrderID = String.valueOf(workOrderID).substring(0, 15);
            String queryStr = 'SELECT ';
            for(Schema.FieldSetMember f : getFields()) {
                queryStr += f.getFieldPath() + ', ';
            }
            if(!queryStr.contains('RecordTypeId'))
                queryStr+='RecordTypeId,';
            queryStr += 'Id, Name FROM Work_Order__c Where id =\''+workOrderID+'\' LIMIT 1';
            
            system.debug(workOrderID+' : queryStr : '+queryStr);
            sourceWorkOrder = Database.query(queryStr);
            if(sourceWorkOrder != null){
                Map<String, Schema.SObjectField> workOrderFieldsMap = Schema.SObjectType.Work_Order__c.fields.getMap();
                Id com = Schema.SObjectType.Work_Order__c.getRecordTypeInfosByName().get('Commercial').getRecordTypeId();
                Id res = Schema.SObjectType.Work_Order__c.getRecordTypeInfosByName().get('Residential').getRecordTypeId();
                Id comIC = Schema.SObjectType.Work_Order__c.getRecordTypeInfosByName().get('Commercial IC').getRecordTypeId();
                Id comICC = Schema.SObjectType.Work_Order__c.getRecordTypeInfosByName().get('Commercial ICC').getRecordTypeId();
                targetWorkOrder = new Work_Order__c();
                targetWorkOrder.recordTypeId = sourceWorkOrder.recordTypeId ;
                for(Schema.FieldSetMember f : getFields()) {
                    if(f.getFieldPath() == 'Van_assignment__c')
                        targetWorkOrder.Van_assignment__c = 'van 5';
                    else if(f.getFieldPath() == 'Status__c'){
                        if((sourceWorkOrder.recordTypeId == com  || sourceWorkOrder.recordTypeId == res)  && (sourceWorkOrder.Status__c =='Invoice Paid' ||sourceWorkOrder.Status__c =='Invoiced' || sourceWorkOrder.Status__c =='Completed' ) )
                            targetWorkOrder.Status__c = 'Pending';
                        else if((sourceWorkOrder.recordTypeId == comIC ) && (sourceWorkOrder.Status__c =='Invoice Paid' || sourceWorkOrder.Status__c =='Invoiced' || sourceWorkOrder.Status__c =='Completed' ))
                            targetWorkOrder.Status__c =  'Pending IC';
                        else if((sourceWorkOrder.recordTypeId == comICC )&& (sourceWorkOrder.Status__c =='Invoice Paid' || sourceWorkOrder.Status__c =='Invoiced' || sourceWorkOrder.Status__c =='Completed' ))
                            targetWorkOrder.Status__c =  'Pending ICC';
                    }else if(f.getFieldPath() != 'Id' && workOrderFieldsMap.get(f.getFieldPath()).getDescribe().isUpdateable())
                        targetWorkOrder.put(f.getFieldPath(), sourceWorkOrder.get(f.getFieldPath()));
                }
            }
            if(targetWorkOrder != null){
                insert targetWorkOrder;
                return  (new PageReference('/'+targetWorkOrder.id));
            }else
                return  (new PageReference('/'+sourceWorkOrder.id));
        }catch(Exception e){
            
        }
        return null;
    }
    
    public List<Schema.FieldSetMember> getFields() {
        return SObjectType.Work_Order__c.FieldSets.Fields_To_Super_Clone.getFields();
    }
    
    
}