force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Work Orders</relationshipLabel>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/accountControllerExtensionTest.cls
@isTest
public class accountControllerExtensionTest {
    @isTest
    static void positiveCase() {
        Account acct = new Account();
        acct.Name = 'Damco';
        acct.Email__c = 'test@damcogroup.com';
        insert acct;
        
        Test.StartTest(); 
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        accountControllerExtension testAcc = new accountControllerExtension(sc);
        PageReference pageRef = Page.accountDelete; // Add your VF page Name here
        pageRef.getParameters().put('id', String.valueOf(acct.Id));
        Test.setCurrentPage(pageRef);
        testAcc.deleteAccounts();
        //testAccPlan.save(); call all your function here
        Test.StopTest();
    }
    @isTest
    static void negativeCase() {
        Account acct = new Account();
        acct.Name = 'Damco';
        acct.Email__c = 'test@damcogroup.com';
        insert acct;
        
        Work_Order__c wtest = new Work_Order__c();
        wtest.Account_Name__c = acct.Id;
        insert wtest;    
        
        Test.StartTest(); 
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        accountControllerExtension testAcc = new accountControllerExtension(sc);
        PageReference pageRef = Page.accountDelete; // Add your VF page Name here
        pageRef.getParameters().put('id', String.valueOf(acct.Id));
        Test.setCurrentPage(pageRef);
        testAcc.deleteAccounts();
        //testAccPlan.save(); call all your function here
        Test.StopTest();
    }
    @isTest
    static void redirect() {
        Account acct = new Account();
        acct.Name = 'Damco';
        acct.Email__c = 'test@damcogroup.com';
        insert acct;
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(acct);
        accountControllerExtension testAcc = new accountControllerExtension(sc);
        PageReference pageRef = Page.accountDelete; // Add your VF page Name here
        pageRef.getParameters().put('id', String.valueOf(acct.Id));
        Test.setCurrentPage(pageRef);
        testAcc.accountRecordView();
    }
}