force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Field_Crew_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Field_Crew_End_Time__c</fullName>
    <inlineHelpText>Auto populated field that captures the time field crew worker clocked out at job</inlineHelpText>
    <label>Field Crew End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Field_Crew_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Field_Crew_Start_Time__c</fullName>
    <inlineHelpText>Auto populated field that captures the time field crew worker clocked in at job</inlineHelpText>
    <label>Field Crew Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GeoLocController.cls
public class GeoLocController {
    @AuraEnabled
    public static string checkIn(String latitude, String longitude, String recId ){
        system.debug('latitude - '+latitude +'longitude= '+longitude +'Record id ='+recId);
        Work_order__c wo = [Select Id,Field_Crew_Start_Time__c,Field_Crew_End_Time__c FROM work_Order__c where id = :recId LIMIT 1];
       //Comment out for temporarily deactivate the GPS functionality and have only the timestamp captured.
       //Dt - 20/08/2024
      
        //wo.Field_Crew_Start_Location__Latitude__s = decimal.valueOf(latitude);
        //wo.Field_Crew_Start_Location__Longitude__s = decimal.valueOf(longitude);
        wo.Field_Crew_Start_Time__c = system.now();
        update wo;
        return 'checkIn success';
    }
    @AuraEnabled
    public static string checkOut(String latitude, String longitude, String recId ){
        system.debug('inside checkout latitude - '+latitude +'longitude= '+longitude +'Record id ='+recId);
        Work_order__c wo = [Select Id,Field_Crew_Start_Time__c,Field_Crew_End_Time__c FROM work_Order__c where id = :recId LIMIT 1];
       //Comment out for temporarily deactivate the GPS functionality and have only the timestamp captured.
       //Dt - 20/08/2024
      
        //wo.Field_Crew_End_Location__Latitude__s = decimal.valueOf(latitude);
        //wo.Field_Crew_End_Location__Longitude__s = decimal.valueOf(longitude);
        wo.Field_Crew_End_Time__c = system.now();
        update wo;
        return 'checkOut success';
    }

}