force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <inlineHelpText>Name of person requesting the clean</inlineHelpText>
    <label>Requested By</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Earliest date to clean carpet</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Van_assignment__c.field-meta.xml
<CustomField>
    <fullName>Van_assignment__c</fullName>
    <label>Van assignment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Van 1</fullName>
                <color>#FFFF66</color>
                <label>Van 1</label>
            </value>
            <value>
                <fullName>Van 2</fullName>
                <color>#CC33CC</color>
                <label>Van 2</label>
            </value>
            <value>
                <fullName>Van 3</fullName>
                <color>#3333FF</color>
                <label>Van 3</label>
            </value>
            <value>
                <fullName>Van 4</fullName>
                <color>#33CC00</color>
                <label>Van 4</label>
            </value>
            <value>
                <fullName>Van 5</fullName>
                <color>#66FF99</color>
                <default>true</default>
                <label>Van 5</label>
            </value>
            <value>
                <fullName>Team Van</fullName>
                <color>#FF9900</color>
                <label>Team Van</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FieldCrewGeoLocation_Test.cls
@isTest
public class FieldCrewGeoLocation_Test {
    @testSetup
    static void testDataCreation(){
        Work_Order__c  work = new Work_Order__c();
        work.Van_assignment__c = 'Van5'; 
        work.Requested_By__c = 'Test';
        work.Start_Date__c = system.today();
        work.OwnerId = UserInfo.getUserId();
        insert work;
        work.Field_Crew_Start_Location__Latitude__s = 28.4417269;
        work.Field_Crew_Start_Location__Longitude__s  = 77.31067139999999;
        update work;
    }
    static testmethod void testCheckInGeoLoc(){
        Work_Order__c wo = [Select id,Van_assignment__c FROM Work_Order__c];
        ApexPages.StandardController sc = new ApexPages.StandardController(wo);
        FieldCrewGeoLocation fc = new FieldCrewGeoLocation(sc);
        ApexPages.currentPage().getParameters().put('LatParam','28.4417269');
        ApexPages.currentPage().getParameters().put('LongParam','77.31067139999999');
        fc.latt = '28.4417269';
        fc.longt = '77.31067139999999';
        fc.request = 'checkin';
        fc.saveCordinates();
    }
    static testmethod void testCheckOutGeoLoc(){
        Work_Order__c wo = [Select id,Van_assignment__c FROM Work_Order__c];
        ApexPages.StandardController sc = new ApexPages.StandardController(wo);
        FieldCrewGeoLocation fc = new FieldCrewGeoLocation(sc);
        ApexPages.currentPage().getParameters().put('LatParam','28.4417269');
        ApexPages.currentPage().getParameters().put('LongParam','77.31067139999999');
        fc.latt = '28.4417269';
        fc.longt = '77.31067139999999';
        fc.request = 'checkout';
        fc.saveCordinates();
    }
}