force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Earliest date to clean carpet</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending IC</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending ICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestWorkOrderExtension.cls
@isTest
Public class TestWorkOrderExtension
{
    TestWorkOrderExtension()
    {
        List<Work_Order__c> workOrderList = [SELECT Name FROM Work_Order__c LIMIT 20];

        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(workOrderList);
        
        WorkOrderExtension objWorkOrderExtension = new WorkOrderExtension(sc);
        objWorkOrderExtension.GetDataFilter();
        objWorkOrderExtension.GetDataPageSize();
        objWorkOrderExtension.PreviousData();
        objWorkOrderExtension.NextData();
        
    }
    
    static testmethod void testWorkOrderExtensionController () 
    {
        List<Work_Order__c> workOrderList = [SELECT Name FROM Work_Order__c LIMIT 20];

        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(workOrderList);
        
        WorkOrderExtension objWorkOrderExtension = new WorkOrderExtension(sc);
        
        objWorkOrderExtension.recordOffset =0;
        objWorkOrderExtension.recordLimit =50;
        //filter='All';
        objWorkOrderExtension.pageNum=2;
        objWorkOrderExtension.sortExpression = 'Start_Date__c';
        objWorkOrderExtension.sortDirection = 'Desc';
        objWorkOrderExtension.filterCondition = ' Status__c = \'Invoice Paid\' ';
        
        
        objWorkOrderExtension.NextData();
        objWorkOrderExtension.PreviousData();
        
        PageReference pRef = Page.Default_Community_Page;
        pRef.getParameters().put('condition', ' Status__c = \'Invoice Paid\' ');
        Test.setCurrentPage(pRef);
        
        //Test.startTest();
        
        objWorkOrderExtension.GetDataFilter();
        objWorkOrderExtension.GetDataPageSize();
        objWorkOrderExtension.getSortDirection();
        objWorkOrderExtension.setSortDirection('');
        //Test.stopTest();
        
        
        
    }  
}