force-app/main/default/objects/Calendar_Colors__c/Calendar_Colors__c.object-meta.xml
<CustomObject>
    <label>Calendar Colors</label>
    <nameField>
        <label>Calendar Colors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Colors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_Colors__c/fields/Back_Color__c.field-meta.xml
<CustomField>
    <fullName>Back_Color__c</fullName>
    <label>Back Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Colors__c/fields/Text_Color__c.field-meta.xml
<CustomField>
    <fullName>Text_Color__c</fullName>
    <label>Text Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Colors__c/fields/Van_Based__c.field-meta.xml
<CustomField>
    <fullName>Van_Based__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Van Based</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Calendar_Objects__c/Calendar_Objects__c.object-meta.xml
<CustomObject>
    <label>Calendar Objects</label>
    <nameField>
        <label>Calendar Objects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <inlineHelpText>Name of person requesting the clean</inlineHelpText>
    <label>Requested By</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Earliest date to clean carpet</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending IC</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending ICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Van_assignment__c.field-meta.xml
<CustomField>
    <fullName>Van_assignment__c</fullName>
    <label>Van assignment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Van 1</fullName>
                <color>#FFFF66</color>
                <label>Van 1</label>
            </value>
            <value>
                <fullName>Van 2</fullName>
                <color>#CC33CC</color>
                <label>Van 2</label>
            </value>
            <value>
                <fullName>Van 3</fullName>
                <color>#3333FF</color>
                <label>Van 3</label>
            </value>
            <value>
                <fullName>Van 4</fullName>
                <color>#33CC00</color>
                <label>Van 4</label>
            </value>
            <value>
                <fullName>Van 5</fullName>
                <color>#66FF99</color>
                <default>true</default>
                <label>Van 5</label>
            </value>
            <value>
                <fullName>Team Van</fullName>
                <color>#FF9900</color>
                <label>Team Van</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Calendar_Colors_ControllerTest.cls
@isTest
Public class Calendar_Colors_ControllerTest
{
    static testMethod void cofigureCalendarColors()
    {
        Id user = UserInfo.getUserId();
        
        system.assertEquals(user, UserInfo.getUserId());
        
        Work_Order__c work;
        work = new Work_Order__c();
        work.Van_assignment__c = 'Van5'; 
        work.Requested_By__c = 'Test';
        work.Start_Date__c = system.today();
        work.OwnerId = UserInfo.getUserId();
        insert work;
        
        Calendar_Colors__c newCalendarColor = new Calendar_Colors__c(Name = 'Test Color Code', Back_Color__c = '#84FF80', Object__c = 'Account, Lead', Status__c = 'In Progress', Text_Color__c = '#FFFFFF', Type__c = 'Task', User__c = user,Van_Based__c = true);
        insert newCalendarColor;
        
        Calendar_Objects__c newCalendarObject = new Calendar_Objects__c(Name = 'Test Object',API_Name__c = 'Work_Order__c');
        insert newCalendarObject;
        
        system.assertEquals(newCalendarColor.Name, 'Test Color Code');
        system.assert(newCalendarColor.Id != null);
      
        Calendar_Colors_Controller configureCalendarColorController = new Calendar_Colors_Controller();
        newCalendarColor.Type__c = 'Event';
        update newCalendarColor;
        Calendar_Colors_Controller configure = new Calendar_Colors_Controller();
        newCalendarColor.Type__c = 'Work_Order__c';
        update newCalendarColor;
        Calendar_Colors_Controller configures = new Calendar_Colors_Controller();
        newCalendarColor.Type__c = 'Campaign';
        update newCalendarColor;
        Calendar_Colors_Controller con = new Calendar_Colors_Controller();
        configureCalendarColorController.addRows();
        configureCalendarColorController.deleteSelectedRows();
        configureCalendarColorController.Save();
        configureCalendarColorController.selectedColorRow = 1;
        configureCalendarColorController.disableUserCheckBox();
        configureCalendarColorController.disableVanCheckBox();
        
    }
}