force-app/main/default/objects/Calendar_Colors__c/Calendar_Colors__c.object-meta.xml
<CustomObject>
    <label>Calendar Colors</label>
    <nameField>
        <label>Calendar Colors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Colors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_Colors__c/fields/Back_Color__c.field-meta.xml
<CustomField>
    <fullName>Back_Color__c</fullName>
    <label>Back Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Colors__c/fields/Selected_User__c.field-meta.xml
<CustomField>
    <fullName>Selected_User__c</fullName>
    <label>Selected User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Colors__c/fields/Text_Color__c.field-meta.xml
<CustomField>
    <fullName>Text_Color__c</fullName>
    <label>Text Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Colors__c/fields/User_Based__c.field-meta.xml
<CustomField>
    <fullName>User_Based__c</fullName>
    <defaultValue>false</defaultValue>
    <label>User Based</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Calendar_Default_Setting__c/Calendar_Default_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Default Settings for the Calendar.</description>
    <label>Calendar Default Settings</label>
</CustomObject>

force-app/main/default/objects/Calendar_Default_Setting__c/fields/Default_Calendar_View__c.field-meta.xml
<CustomField>
    <fullName>Default_Calendar_View__c</fullName>
    <label>Default Calendar View</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Default_Setting__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Calendar_Default_Setting__c/fields/Show_Active_Campaigns_Only__c.field-meta.xml
<CustomField>
    <fullName>Show_Active_Campaigns_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Active Campaigns Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Calendar_Default_Setting__c/fields/Show_Events__c.field-meta.xml
<CustomField>
    <fullName>Show_Events__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Calendar_Default_Setting__c/fields/Show_Historical_Events__c.field-meta.xml
<CustomField>
    <fullName>Show_Historical_Events__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Historical Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Calendar_Default_Setting__c/fields/Show_Open_Tasks_Only__c.field-meta.xml
<CustomField>
    <fullName>Show_Open_Tasks_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Open Tasks Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Calendar_Default_Setting__c/fields/Show_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Show_Tasks__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Tasks</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Calendar_Default_Setting__c/fields/Show_Todays_Events__c.field-meta.xml
<CustomField>
    <fullName>Show_Todays_Events__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Todays Events</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Calendar_Event_Fields__c/Calendar_Event_Fields__c.object-meta.xml
<CustomObject>
    <label>Calendar Event Fields</label>
    <nameField>
        <label>Calendar Event Fields Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Event Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_Selected_Objects__c/Calendar_Selected_Objects__c.object-meta.xml
<CustomObject>
    <label>Calendar Selected Objects</label>
    <nameField>
        <label>Calendar Selected Objects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Selected Objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_Selected_Users__c/Calendar_Selected_Users__c.object-meta.xml
<CustomObject>
    <label>Calendar Selected Users</label>
    <nameField>
        <label>Calendar Selected Users Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Selected Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Calendar_Selected_Vans__c/Calendar_Selected_Vans__c.object-meta.xml
<CustomObject>
    <label>Calendar Selected Vans</label>
    <nameField>
        <label>Calendar Selected Users Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Calendar Selected Vans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <inlineHelpText>Band width for calendar event</inlineHelpText>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <inlineHelpText>Name of person requesting the clean</inlineHelpText>
    <label>Requested By</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Earliest date to clean carpet</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <inlineHelpText>Setting band width for calendar event</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending IC</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending ICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Van_assignment__c.field-meta.xml
<CustomField>
    <fullName>Van_assignment__c</fullName>
    <label>Van assignment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Van 1</fullName>
                <color>#FFFF66</color>
                <label>Van 1</label>
            </value>
            <value>
                <fullName>Van 2</fullName>
                <color>#CC33CC</color>
                <label>Van 2</label>
            </value>
            <value>
                <fullName>Van 3</fullName>
                <color>#3333FF</color>
                <label>Van 3</label>
            </value>
            <value>
                <fullName>Van 4</fullName>
                <color>#33CC00</color>
                <label>Van 4</label>
            </value>
            <value>
                <fullName>Van 5</fullName>
                <color>#66FF99</color>
                <default>true</default>
                <label>Van 5</label>
            </value>
            <value>
                <fullName>Team Van</fullName>
                <color>#FF9900</color>
                <label>Team Van</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Calendar_ControllerTest.cls
@isTest
Public class Calendar_ControllerTest
{
    static testMethod void calendarTest()
    {
        List<Calendar_Default_Setting__c> defaultSettingList;
        Calendar_Controller calendarControllerObj;

        Work_Order__c work;
        work = new Work_Order__c();
        work.Van_assignment__c = 'Van5'; 
        work.Requested_By__c = 'Test';
        work.Start_Date__c = system.today();
        work.OwnerId = UserInfo.getUserId();
        insert work; 
       
        system.assert(work.Id != null);
        
        Event event;
        event = new Event();
        event.Subject = 'Test Event';
        event.Location = 'Test Location';
        event.Description = 'Test Description'; 
        event.StartDateTime = datetime.now();
        event.EndDateTime = datetime.now().addHours(1);
        event.OwnerId = UserInfo.getUserId();
        event.IsPrivate = false;
        event.Whatid = work.Id;
        insert event;
        system.debug(event);
        Map<Id,Event> eventMap=new Map<Id,Event>();
        eventMap.put(event.id,event);
        system.assert(event.Id != null);
        
        Task task;
        task = new Task();
        task.Subject = 'Test Task';
        task.Status = 'In Progress';
        task.ActivityDate = Date.Today(); 
        task.ReminderDateTime = DateTime.now(); 
        task.Priority = 'High';
        task.OwnerId = UserInfo.getUserId();
        task.WhatId = work.Id;
        insert task;     
        
        system.assert(task.Id != null);
        
        calendarControllerObj = new Calendar_Controller();
        calendarControllerObj.createDefaultColors();
        
        Calendar_Default_Setting__c defaultSetting = new Calendar_Default_Setting__c ();
        defaultSetting.Name = UserInfo.getUserId();        
        defaultSetting.Show_Campaigns__c = true;
        defaultSetting.Show_Active_Campaigns_Only__c = false;
        defaultSetting.Default_Calendar_View__c = 'month';
        defaultSetting.Show_Events__c = true; 
        defaultSetting.Show_Historical_Events__c = true; 
        defaultSetting.Show_Open_Tasks_Only__c = false;
        defaultSetting.Show_Tasks__c = true;
        defaultSetting.Show_Todays_Events__c = false;
        defaultSetting.Start_Time__c = '09:00';
        defaultSetting.End_Time__c = '17:00';
        defaultSetting.User_Id__c = UserInfo.getUserId();
        insert defaultSetting;
        
        system.assert(defaultSetting.Id != null);
        
        Calendar_Colors__c calColors = new Calendar_Colors__c();
        calColors.Name = 'Color1'; 
        calColors.Back_Color__c = 'Black'; 
        calColors.Object__c = 'All'; 
        calColors.Status__c = 'All'; 
        calColors.Text_Color__c = 'White';
        calColors.Type__c = 'All';
        calColors.User__c = UserInfo.getUserId();        
        insert calColors; 
        
        system.assertEquals(calColors.Name, 'Color1');
        system.assert(calColors.Id != null);
        
        calColors = new Calendar_Colors__c();
        calColors.Name = 'Color2'; 
        calColors.Back_Color__c = 'Black'; 
        calColors.Object__c = 'All'; 
        calColors.Status__c = 'All'; 
        calColors.Text_Color__c = 'White';
        calColors.Type__c = 'Task';
        calColors.User__c = UserInfo.getUserId();        
        insert calColors; 
        
        system.assertEquals(calColors.Name, 'Color2');
        system.assert(calColors.Id != null);
        
        calColors = new Calendar_Colors__c();
        calColors.Name = 'Color3'; 
        calColors.Back_Color__c = 'Black'; 
        calColors.Object__c = 'All'; 
        calColors.Status__c = 'All'; 
        calColors.Text_Color__c = 'White';
        calColors.Type__c = 'Event';
        calColors.User__c = UserInfo.getUserId();  
        calColors.User_Based__c = true;
        calColors.Selected_User__c = UserInfo.getUserId(); 
        insert calColors; 
        
        calColors = new Calendar_Colors__c();
        calColors.Name = 'Color3'; 
        calColors.Back_Color__c = 'Black'; 
        calColors.Object__c = 'All'; 
        calColors.Status__c = 'All'; 
        calColors.Text_Color__c = 'White';
        calColors.Type__c = 'Work_Order__c';
        calColors.User__c = UserInfo.getUserId();  
        calColors.User_Based__c = true;
        calColors.Selected_User__c = UserInfo.getUserId(); 
        insert calColors; 

        Calendar_Event_Fields__c cef =  new Calendar_Event_Fields__c(API_Name__c = 'Priority', Field_Name__c = 'Priority',Object__c = 'Task',Order__c = 0, Name = 'Task-Priority');
        insert cef;
        
        Calendar_Event_Fields__c cef1 = new Calendar_Event_Fields__c(API_Name__c = 'Van_assignment__c', Field_Name__c = 'Van_assignment__c', Object__c = 'Work_Order__c',Order__c = 0, Name = 'WorkOrder-Name');
        insert cef1;
        insert new Calendar_Event_Fields__c(API_Name__c = 'Subject', Field_Name__c = 'Subject',Object__c = 'Event',Order__c = 0, Name = 'Event-Subject');
        
        system.assertEquals(calColors.Name, 'Color3');
        system.assert(calColors.Id != null);
        
        Calendar_Selected_Users__c users = new Calendar_Selected_Users__c();
        users.User_Id__c = UserInfo.getUserId();
        insert users;
        
        Calendar_Selected_Objects__c obj = new Calendar_Selected_Objects__c();
        obj.User_Id__c = UserInfo.getUserId();
        insert obj;
        
        Calendar_Selected_Vans__c vans = new Calendar_Selected_Vans__c();
        vans.User_Id__c = UserInfo.getUserId();
        insert vans;
       
        calendarControllerObj = new Calendar_Controller();
        calendarControllerObj.currentEventId = event.id;
        calendarControllerObj.showEvents = true;
        calendarControllerObj.flag = true;
        calendarControllerObj.backColor = '';
        calendarControllerObj.textColor = '';
        calendarControllerObj.currentUserId = UserInfo.getUserId();
        calendarControllerObj.createDefaultColors();
        
        calendarControllerObj.getObjectOptions();
        calendarControllerObj.getCalendarData();
        calendarControllerObj.getResourceData();
        calendarControllerObj.saveDefaults();
        
        cef.API_Name__c = 'WhatId';
        update cef;
        cef1.API_Name__c = 'OwnerId';
        update cef1;
        system.debug(cef1);
        calendarControllerObj.getCalendarData();
        calendarControllerObj.getResourceData();
        
        calendarControllerObj.newResourceId = string.valueOf(UserInfo.getUserId());
        calendarControllerObj.newStartTime = string.valueOf(DateTime.Now());
        calendarControllerObj.newEndTime = string.valueOf(DateTime.Now().addHours(2)); 
        calendarControllerObj.currentEventId = task.Id;
        calendarControllerObj.updateEvent();
        
        calendarControllerObj.newResourceId = string.valueOf(UserInfo.getUserId());
        calendarControllerObj.newStartTime = string.valueOf(DateTime.Now());
        calendarControllerObj.newEndTime = string.valueOf(DateTime.Now().addHours(2)); 
        calendarControllerObj.currentEventId = event.Id;
        calendarControllerObj.updateEvent();
        
        calendarControllerObj.newResourceId = string.valueOf(work.Van_assignment__c);
        calendarControllerObj.newStartTime = string.valueOf(DateTime.Now());
        calendarControllerObj.newEndTime = string.valueOf(DateTime.Now().addHours(2)); 
        calendarControllerObj.backColor = '';
        calendarControllerObj.textColor = '';
        calendarControllerObj.currentEventId = work.Id;
		
        
        calendarControllerObj.getSchedule();
        Calendar_Controller.getSalesforce1();
        calendarControllerObj.getAvailableViews();
        calendarControllerObj.getCalendarVans();
        calendarControllerObj.getCalendarUsers();
        calendarControllerObj.getEventColor(event,task,work);
    }
}