force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Card_Brand__c.field-meta.xml
<CustomField>
    <fullName>Card_Brand__c</fullName>
    <label>Card Brand</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Card_Type__c</fullName>
    <label>Card Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Entry_Method__c.field-meta.xml
<CustomField>
    <fullName>Entry_Method__c</fullName>
    <label>Entry Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Error_Category__c.field-meta.xml
<CustomField>
    <fullName>Error_Category__c</fullName>
    <label>Error Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Error_Detail__c.field-meta.xml
<CustomField>
    <fullName>Error_Detail__c</fullName>
    <label>Error Detail</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Expiry_Month__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Month__c</fullName>
    <label>Expiry Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Expiry_Year__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Year__c</fullName>
    <label>Expiry Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Last_4_Digit__c.field-meta.xml
<CustomField>
    <fullName>Last_4_Digit__c</fullName>
    <label>Last 4 Digit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Creation_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Creation_Date__c</fullName>
    <label>Payment Creation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/PaymentID__c.field-meta.xml
<CustomField>
    <fullName>PaymentID__c</fullName>
    <label>PaymentID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <label>Work Order</label>
    <referenceTo>Work_Order__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SquareAPI__c/SquareAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SquareAPI</label>
</CustomObject>

force-app/main/default/objects/SquareAPI__c/fields/ApplicationId__c.field-meta.xml
<CustomField>
    <fullName>ApplicationId__c</fullName>
    <label>ApplicationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SquareAPI__c/fields/EndpointURL__c.field-meta.xml
<CustomField>
    <fullName>EndpointURL__c</fullName>
    <label>EndpointURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SquareAPI__c/fields/LocationId__c.field-meta.xml
<CustomField>
    <fullName>LocationId__c</fullName>
    <label>LocationId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/Work_Order__c.object-meta.xml
<CustomObject>
    <description>External Work Order Information</description>
    <label>Work Order</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Work_Order__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Balance_Due1__c.field-meta.xml
<CustomField>
    <fullName>Balance_Due1__c</fullName>
    <formula>Sub_Total__c - Discount_Amount_NEW__c + (Tax__c * (Sub_Total__c - Discount_Amount_NEW__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance Due</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Invoice_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Frequency__c</fullName>
    <label>Invoice Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
                <default>true</default>
                <label>Single</label>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
            </value>
            <value>
                <fullName>Invoice Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Pending IC</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Pending ICC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Work_Order__c/fields/Work_Order__c.field-meta.xml
<CustomField>
    <fullName>Work_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Work Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Work_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PaymentController.cls
public class PaymentController{
    public string paymentCode{get;set;}
    public boolean paymentSuccess{get;set;}
    public string paymentResponse{get;set;}
    public Work_Order__c workOrderObj {get;set;}
    public Decimal payabletAmt {get;set;}
    public String workOrderId  {get;set;}
    public String applicationID {get;set;}
    public String locationID {get;set;}
            
    public PaymentController() {
        try
        {
            paymentSuccess = false;
            workOrderId = ApexPages.currentPage().getParameters().get('id');
            workOrderObj = [SELECT Id,Name,Balance_Due1__c,Invoice_Frequency__c,OwnerId From Work_Order__c Where id = :workOrderId and Invoice_Frequency__c = 'Single'Limit 1];
            if(workOrderObj != null && workOrderObj.Balance_Due1__c != null)
            {
                payabletAmt = workOrderObj.Balance_Due1__c;
                applicationID = SquareAPI__c.getInstance(workOrderObj.OwnerId).ApplicationId__c;
                locationID = SquareAPI__c.getInstance(workOrderObj.OwnerId).LocationId__c;
            }
        }
        catch(Exception e)
        {
            System.debug('Error PaymentController.....' + e.getMessage());
            paymentResponse = e.getMessage();
        }
    }
    public void makePayment(){
        try
        {
            if(workOrderObj != null && workOrderObj.Balance_Due1__c > 0)
            {
                System.debug('!!!!!'+workOrderObj);
                Http http = new Http();
                HttpRequest request = new HttpRequest();             
                request.setEndpoint(SquareAPI__c.getInstance(workOrderObj.OwnerId ).EndpointURL__c);            
                request.setHeader('Authorization', 'Bearer ' + SquareAPI__c.getInstance(workOrderObj.OwnerId ).Token__c);
                request.setMethod('POST');
                request.setHeader('Accept', 'application/json');
                request.setHeader('Content-Type', 'application/json;charset=UTF-8');
                Blob b = Crypto.GenerateAESKey(128);
                String h = EncodingUtil.ConvertTohex(b);
                String uniqueKey = h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
                
                request.setBody('{"idempotency_key": "' + uniqueKey + '","source_id": "' + paymentCode +'","autocomplete":true,"amount_money":{"amount" : ' + (payabletAmt * 100) + ',"currency":"USD"}}');                
                //Adding as payabletAmt * 100 part of prod case as API accepts amt in cent
                
                System.debug('request.Body............' +  request.getBody());
                
                HttpResponse response = http.send(request);
                System.debug('response.Body............' +  response.getBody());
                if(response.getBody() != null)
                {
                    paymentSuccess = true;
                    PaymentResponseWrapper paymentResObj = (PaymentResponseWrapper)JSON.deserialize(response.getBody(),PaymentResponseWrapper.class);
                    
                    if(response.getStatusCode() == 200)
                    {
                        paymentResponse = 'Thank you for making payment.We appreciate your Business!';
                        //create payment detail record
                        Payment__c paymentObj = new Payment__c();
                        paymentObj.PaymentID__c = paymentResObj.payment.id;
                        paymentObj.Card_Type__c = paymentResObj.payment.card_details.card.card_type;
                        paymentObj.Entry_Method__c = paymentResObj.payment.card_details.entry_method;
                        paymentObj.Expiry_Month__c = paymentResObj.payment.card_details.card.exp_month;
                        paymentObj.Expiry_Year__c = paymentResObj.payment.card_details.card.exp_year;
                        paymentObj.Last_4_Digit__c = paymentResObj.payment.card_details.card.last_4;
                        paymentObj.Card_Brand__c = paymentResObj.payment.card_details.card.card_brand;
                        paymentObj.Order_ID__c = paymentResObj.payment.order_id;
                        paymentObj.Payment_Creation_Date__c = paymentResObj.payment.created_at;
                        paymentObj.Receipt_Number__c = paymentResObj.payment.receipt_number;
                        paymentObj.Source_Type__c = paymentResObj.payment.source_type;
                        paymentObj.Status__c = paymentResObj.payment.status;
                        paymentObj.Work_Order__c = workOrderId;
                        paymentObj.Amount__c = paymentResObj.payment.amount_money.amount / 100;
                        insert paymentObj;
                    }
                    else
                    {
                        paymentResponse = paymentResObj.errors[0].detail;
                        Payment__c paymentObj = new Payment__c();
                        paymentObj.Error_Category__c = paymentResObj.errors[0].category;
                        paymentObj.Error_Code__c = paymentResObj.errors[0].code;
                        paymentObj.Error_Detail__c = paymentResObj.errors[0].detail;
                        paymentObj.Work_Order__c = workOrderId;
                        insert paymentObj;
                    }
                }
            }      
        }
        catch(Exception e)
        {
            System.debug('Error PaymentController:makePayment().....' + e.getMessage());
            paymentResponse = e.getMessage();
        }
    }
}